// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxlB-xJRzyyp3XPpx_u75M56Im4DjCL4A',
    appId: '1:444481156041:web:3195a2a427b5616b78ee18',
    messagingSenderId: '444481156041',
    projectId: 'cinemate-cdc28',
    authDomain: 'cinemate-cdc28.firebaseapp.com',
    storageBucket: 'cinemate-cdc28.appspot.com',
    measurementId: 'G-YDF3RVB0LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51T5up9lUzAZg6ROeHFWfQ3zD3cGMUdM',
    appId: '1:444481156041:android:41f1024ee0eaaef078ee18',
    messagingSenderId: '444481156041',
    projectId: 'cinemate-cdc28',
    storageBucket: 'cinemate-cdc28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoRQE_7w2AHPQwEp73vOQGjijnaVLZm9M',
    appId: '1:444481156041:ios:e3feb98cdb54546e78ee18',
    messagingSenderId: '444481156041',
    projectId: 'cinemate-cdc28',
    storageBucket: 'cinemate-cdc28.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoRQE_7w2AHPQwEp73vOQGjijnaVLZm9M',
    appId: '1:444481156041:ios:938a0db79c7c322878ee18',
    messagingSenderId: '444481156041',
    projectId: 'cinemate-cdc28',
    storageBucket: 'cinemate-cdc28.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
